# Site settings
title: "Havee's Space"
url: "//havee.me"
paginate: 5
author:
    name: Havee
    github:
    email:
    gitcafe:
    twitter:
    facebook:
    googleplus:
    weibo:
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
kramdown:
    input: GFM
permalink: /:categories/:year-:month/:title.html
gems: [jekyll-paginate]
exclude: [Gemfile, Gemfile.lock, qrsync, Rakefile, README.md, docker-compose.yml]
assets_path: /assets
cdn: "//cdn.09hd.com"
sass:
    sass_dir: assets/_sass
    style: :compressed

# collections
collections:
    tools:
        output: true
        permalink: /:path/:title.html

# comment
comments:
    duoshuo:
        name:
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26

# 网站统计
analytics:
    baidu:
        siteid:         # 百度统计 js 代码后的字符串
webmaster:
    baidu:
        verify: BvD3CNBzK6
    google:
        verify: oE8rOfWaq0A-pkv0HY170kkzgB1hM1j6zRTyRBgRw78
    bing:
        verify: FE0D1D87A075E1003B82C7446EE360ED
