# Site settings
title: "Havee's Space"
keywords: "linux, gentoo, internet, sql, jekyll, BSD, MAC, havee"
description: "Havee Hobbies, Knowledge Records。"
url: "//havee.me"
highlighter: pygments
paginate: 5
author:
    name: Havee
    github: Ihavee
    email:
    gitcafe: Havee
    twitter:
    facebook:
    googleplus:
    weibo: Havanna
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
permalink: /:categories/:year-:month/:title.html

assets_path: /assets
sass:
    sass_dir: assets/_sass
    style: :compressed

# comment
comments:
    duoshuo:
        name: havanna
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26
# 网站统计
analytics:
    baidu:
        siteid: 707c49682d45342c4abaa7f2fbdd23dd        # 百度统计 js 代码后的字符串

