# Site settings
title: "Havee's Space"
url: "//havee.me"
highlighter: pygments
paginate: 5
author:
    name: Havee
    github:
    email:
    gitcafe:
    twitter:
    facebook:
    googleplus:
    weibo:
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough", "no_intra_emphasis"]
permalink: /:categories/:year-:month/:title.html

assets_path: /assets
cdn: "//cdn.09hd.com"
sass:
    sass_dir: assets/_sass
    style: :compressed

# comment
comments:
    duoshuo:
        name: havanna
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26

# 网站统计
analytics:
    baidu:
        siteid: 625169d97c95b10732a31bbe33aa305d        # 百度统计 js 代码后的字符串

